### ISSUE TITLE
Feedback by Aaron Briggs

### ISSUE THREAD

**Issue by abriggs3** [miarnold/projectMackArnold#5]
# Design/Code Review 2

#### Reviewer: Aaron Briggs

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|  |  |
|**Application Functionality**|1. At least 25% of the application's target functionality has been built and is working. </br>2. In comments/suggestions field list and evaluate the functionality that has been implemented.  | 2| Seems to be on track. The DOAs are there and tested, which is a major component. So the basic structure is there, another couple hundred hours of work and it will be done. Suggestion, quit your job, put your time in where it matters:)
|**Unit Tests**|1. Code coverage stats meets or exceeds the developer's code coverage goal. <br> 2. Unit tests are meaningful - they test the business logic and data access aspects of the application (simple methods like getters and setters are not tested) </br> 3. In comments/suggestions field list the code coverage goal and actual current coverage percentage. <br>4. @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code, like creation of entities.<br>5. A test database is used for unit testing and data is cleaned up/reset before or after the tests, so that the tests are re-runnable without developer intervention/cleanup. | 2| The tests for the DOAs worked and used the correct @Before annotations. However, some failed when ran as a suite. Suggestion, add implementation to rebuild the test db, or have the tests run a line after the 'assert' statement to return the db to the previous state.
|**JSPs**|1. Templating is used to eliminate rundandant code(for example, header.jsp, footer.jsp, etc.) <br> 2. CSS or a CSS framework has been implemented to give the site a professional look and feel<br> 3. There is not any embedded java code in the JSPs (EL and JSTL is used appropriately).| 3| Everything is looking good here. Form and CSS templates are used and no Java code is mixed in the HTML. Suggestion, I miss the original gold/mustard color background color--it was a bold choice. Go back to that (just a suggestion).   
|**Code quality**|1. Methods are single-purpose<br> 2. Classes appropriately-sized classes (no monster classes). </br > 3. Methods do not contain many branches or loops that could be simplified or broken up into smaller methods. <br /> 4. The same lines of code are not repeated at all <br> 5. Uses interfaces/super/subclass relationships rather than repeating functionality in multiple classes? For example, using a generic/abstract dao. <br />6. Code does not contain any hard-coded values that should be in a properties file </br> 7. Appropriate logging levels are used. Info, debug, error, etc. </br> 8. There are not any System.out.println() or printStackTrace() statements in the code </br> 9. Package, class, method and variable names are descriptive and meaningful. <br/>10. Include in the comments section what technique you used to evaluate the items above. Using a code quality plug-in is highly recommended as a starting point for code quality reviews. | 3| At the moment the most of the implemented code is in the DOAs. This code seems well thought out and efficient in design. There are no mega-methods and little repetition. Suggestion, a generic DOA might be nice. Psst-I know a couple people with a working copy. |
|**Web Service/API integration**|1. Web service/api has been identified in the project problem statement/list of technologies. </br> 2. Web Service integration has been built. <br /> 3. Web Service integration has been unit tested. | 1| At this point the web service implementation is still just a dream. Suggestion, again, quit your job.|
|**Independent research topic**| 1. Topic has been identified in the project problem statement/list of technologies. </br> 2. Topic research is complete and documented. <br /> 3. Topic has been implemented in the project| 2| This section is postponed until the basic functionality of the project as been implemented. But the concept seems interesting.|  
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.|3|1. These projects are time consuming for everyone. So, not being where you want to be with it is more the norm than the exception. 2. Testing the methods using the DB can be problematic without rebuilding the DB. 3. There are several ways to get data from the DB.

**Comment by pawaitemadisoncollege** [comment]
Aaron - thanks for the humor :)
