### ISSUE TITLE
Code review 2 feedback from Sam Soper

### ISSUE THREAD

**Issue by ssoperMadisonCollege** [miarnold/projectMackArnold#6]
# Design/Code Review 2

#### Reviewer: Sam Soper

|Item |Criteria|Rating | Comments/Suggestions|
|--------|---------|---------------|---|
||| Use the following scale:<br> 1= It needs more work<br>  2 = Somewhat<br> 3 = Yes it is great|Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|  |  |
|**Application Functionality**|1. At least 25% of the application's target functionality has been built and is working. </br>2. In comments/suggestions field list and evaluate the functionality that has been implemented.  | 2 | Mack is on track and has most of the project scaffolding in place to start doing the "fun" coding.  One suggestion would be to research the Edmunds API to see if you can pull mileage/gas price/cost stats for car models.  Another suggestion would be to add some of the unecessary-to-track information in your project (like logs, the .idea directory) to the .gitignore.
|**Unit Tests**|1. Code coverage stats meets or exceeds the developer's code coverage goal. <br> 2. Unit tests are meaningful - they test the business logic and data access aspects of the application (simple methods like getters and setters are not tested) </br> 3. In comments/suggestions field list the code coverage goal and actual current coverage percentage. <br>4. @Before/@BeforeClass/@After/@AfterClass used to reduce redundant code, like creation of entities.<br>5. A test database is used for unit testing and data is cleaned up/reset before or after the tests, so that the tests are re-runnable without developer intervention/cleanup. | 2 | The unit tests are present for User and Car DAOs.  Code coverage is good for those classes - but it would be beneficial to set up your tests so you can safely delete users without inserting them again.  I would also suggest adding unit tests for more of your java classes in the main packages to broaden code coverage.
|**JSPs**|1. Templating is used to eliminate rundandant code(for example, header.jsp, footer.jsp, etc.) <br> 2. CSS or a CSS framework has been implemented to give the site a professional look and feel<br> 3. There is not any embedded java code in the JSPs (EL and JSTL is used appropriately).| 3 | Mack has a ton of JSPs in place and linked together properly.  He also has templates (like a sidebar, header, etc.) installed to reduce redundant code.  Nice work!  One suggestion would be to perhaps separate these JSPs into directory hierarchies to make it a little easier to find the one you're looking for when you need to edit them.  Other developers who work on your code will thank you for your organizational prowess.
|**Code quality**|1. Methods are single-purpose<br> 2. Classes appropriately-sized classes (no monster classes). </br > 3. Methods do not contain many branches or loops that could be simplified or broken up into smaller methods. <br /> 4. The same lines of code are not repeated at all <br> 5. Uses interfaces/super/subclass relationships rather than repeating functionality in multiple classes? For example, using a generic/abstract dao. <br />6. Code does not contain any hard-coded values that should be in a properties file </br> 7. Appropriate logging levels are used. Info, debug, error, etc. </br> 8. There are not any System.out.println() or printStackTrace() statements in the code </br> 9. Package, class, method and variable names are descriptive and meaningful. <br/>10. Include in the comments section what technique you used to evaluate the items above. Using a code quality plug-in is highly recommended as a starting point for code quality reviews. | 3 | Methods, variables, and class names are all easy to follow and are well named.  Methods are consice and do one thing at a time.  No same-lines-repeated code. One suggestion would be to try implementing generic dao testing to cut down on some of that redundant testing code.  Another suggestion would be to increase overall logging, especially where you're throwing/catching exceptions with some helpful hints so you can narrow in on bug fixes more easily. |
|**Web Service/API integration**|1. Web service/api has been identified in the project problem statement/list of technologies. </br> 2. Web Service integration has been built. <br /> 3. Web Service integration has been unit tested. | 2 | Mack already has google maps API implemented into one of his JSPs, which looks great!  A suggested next step would be to research how you would unit test this API.  Another suggestion would be to think about how you would integrate your Routes with this API. |
|**Independent research topic**| 1. Topic has been identified in the project problem statement/list of technologies. </br> 2. Topic research is complete and documented. <br /> 3. Topic has been implemented in the project| 1 |  Mack has AWS relational database listed as his independent research topic but has yet to implement it.  I think this pretty normal for everyone in the class so far.  My suggestion would be to google "AWS relational database quickstart guide" to see if there's something quick and dirty to get started with. |  
|**Key takeaways**|List at least 3 things you learned while reviewing this project that will help you in your own project.| 3 | 1) Mack is a database pro, and I need to pick his brain about how to do sql dumps so I can more easily build/rebuild my test database for my unit tests. 2) I would like to pick Mack's brain about how he got all the servlet/JSP/redirect stuff working in his controller package - I haven't done much of this and don't remember much of it from Advanced Java. 3) I need to pick Mack's brain about how to integrate the google API - I will probably try to use the google calendar API and his knowledge on the subject would be very helpful.

**Comment by ssoperMadisonCollege** [comment]
Nice job Mack!

**Comment by pawaitemadisoncollege** [comment]
Sam, you provided some very good insight here. Well done!
